### PR TITLE
Closes #70.

### LINKED ISSUE #70: Make search terms in quotes an exact match, not split out
Currently the search terms are split on every space. Text in quotes should not be split.

### PR DESCRIPTION
**Pull request by nwalke**
Added the ability to search by multi-word terms using double quotes.

### CODE REVIEW

**Comment by ssddanbrown** [comment]
@nwalke Hi again, Thanks again for all the pull requests :+1: , I'll review & merge over the weekend.
I've seen you've been fixing a lot of the issues marked for the next release, Don't worry about #54 since I've pretty much finished it on the [custom_role_system](https://github.com/ssddanbrown/BookStack/compare/custom_role_system) branch. Just got to write a good amount of tests and clean it up a little before merging it back it.

**Comment by nwalke** [comment]
Yeah, I saw!  Should be good stuff.

**Comment by nwalke** [comment]
Wow, I just realized this is horribly broken.  Sorry about that...   

The logic used to turn terms into strings kind of ruins what I was hoping I could easily do.  I'll fix that up.

**Comment by nwalke** [comment]
Awesome!

**Comment by ssddanbrown** [comment]
@nwalke Yeah, I saw the issue, That's a right pain. Since using PDO quoting for escaping doesn't seem to play well with full text searches I've added some custom escaping. I'm a little nervous about it but I've tested loads of combinations of symbols and characters against it (Trying to inject SQL) and it appears to be work fine. I'll still need to test it against mariaDB before release to ensure there's no differences there.

I also learnt that MySQL won't fulltext search exactly against a phrase. Searching `"the tree"` would match against `the tree` and `the old tree`. Any number of words could be between them. I've added some `LIKE` queries which are used if any quoted terms are in the search query to resolve this. I found that doing a fulltext match then a `LIKE` query has minimal performance impact and is still way faster than only using a `LIKE` query.

**Pull request merged**
